---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: 2.1-sdk

inputs:
- name: service-checkout
- name: version

outputs:
- name: service-build

caches:
  - path: nuget

run:
  path: service-checkout/ci/tasks/build-service.sh
