---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet:2.0.3-sdk

inputs:
- name: service-checkout
- name: version

outputs:
- name: service-build

caches:
  - path: nuget

run:
  path: service-checkout/ci/tasks/build-service.sh
