---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet:2.0.3-sdk

inputs:
- name: service-checkout
- name: candidate-release
- name: version

outputs:
- name: service-deploy

run:
  path: service-checkout/ci/tasks/prepare-manifest.sh
