---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: micsosoft/dotnet
    tag: 2.1-sdk

inputs:
- name: service-checkout

caches:
  - path: nuget

run:
  path: service-checkout/ci/tasks/unit-test.sh
